// Generated by gencpp from file cha2_tutorials/cha2_srv1.msg
// DO NOT EDIT!


#ifndef CHA2_TUTORIALS_MESSAGE_CHA2_SRV1_H
#define CHA2_TUTORIALS_MESSAGE_CHA2_SRV1_H

#include <ros/service_traits.h>


#include <cha2_tutorials/cha2_srv1Request.h>
#include <cha2_tutorials/cha2_srv1Response.h>


namespace cha2_tutorials
{

struct cha2_srv1
{

typedef cha2_srv1Request Request;
typedef cha2_srv1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cha2_srv1
} // namespace cha2_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cha2_tutorials::cha2_srv1 > {
  static const char* value()
  {
    return "2a5c7a37218262bae4fcfaa1007692aa";
  }

  static const char* value(const ::cha2_tutorials::cha2_srv1&) { return value(); }
};

template<>
struct DataType< ::cha2_tutorials::cha2_srv1 > {
  static const char* value()
  {
    return "cha2_tutorials/cha2_srv1";
  }

  static const char* value(const ::cha2_tutorials::cha2_srv1&) { return value(); }
};


// service_traits::MD5Sum< ::cha2_tutorials::cha2_srv1Request> should match 
// service_traits::MD5Sum< ::cha2_tutorials::cha2_srv1 > 
template<>
struct MD5Sum< ::cha2_tutorials::cha2_srv1Request>
{
  static const char* value()
  {
    return MD5Sum< ::cha2_tutorials::cha2_srv1 >::value();
  }
  static const char* value(const ::cha2_tutorials::cha2_srv1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::cha2_tutorials::cha2_srv1Request> should match 
// service_traits::DataType< ::cha2_tutorials::cha2_srv1 > 
template<>
struct DataType< ::cha2_tutorials::cha2_srv1Request>
{
  static const char* value()
  {
    return DataType< ::cha2_tutorials::cha2_srv1 >::value();
  }
  static const char* value(const ::cha2_tutorials::cha2_srv1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cha2_tutorials::cha2_srv1Response> should match 
// service_traits::MD5Sum< ::cha2_tutorials::cha2_srv1 > 
template<>
struct MD5Sum< ::cha2_tutorials::cha2_srv1Response>
{
  static const char* value()
  {
    return MD5Sum< ::cha2_tutorials::cha2_srv1 >::value();
  }
  static const char* value(const ::cha2_tutorials::cha2_srv1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::cha2_tutorials::cha2_srv1Response> should match 
// service_traits::DataType< ::cha2_tutorials::cha2_srv1 > 
template<>
struct DataType< ::cha2_tutorials::cha2_srv1Response>
{
  static const char* value()
  {
    return DataType< ::cha2_tutorials::cha2_srv1 >::value();
  }
  static const char* value(const ::cha2_tutorials::cha2_srv1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHA2_TUTORIALS_MESSAGE_CHA2_SRV1_H
